In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
numbers_from_one_to_twenty = np.arange(1, 21)
ones = np.ones(20, )
result = pow((2 * ones), numbers_from_one_to_twenty) / numbers_from_one_to_twenty
result

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
n = 5
power_pow_3 = 3 * np.arange(1, n + 1)
power_pow_4 = 4 * np.arange(1, n + 1)

ones01 = 0.1 * np.ones(n,)
ones02 = 0.2 * np.ones(n, )

np.sum(pow(ones01, power_pow_3) * pow(ones02, power_pow_4))

1.6000025600040968e-06

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
result = np.zeros((8, 8))
evens = np.arange(0, 8, 2)
odds = np.arange(1, 8, 2)

result[evens, :] = np.arange(0, 8) % 2
result[odds, :] = np.arange(1, 9) % 2

result

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [5]:
X = np.random.random((5, 2))

radius = np.sum(X ** 2, axis=1) ** 0.5
X[:,0] = radius
X[:,1] = np.arcsin(X[:,1] / radius)
X

array([[1.26840595, 0.90221823],
       [0.75614993, 0.36059931],
       [0.40166605, 0.38392845],
       [0.9339177 , 0.19306445],
       [1.12032571, 0.99394903]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [6]:
X = np.random.random((10, 10))

argmax = X.flat[np.argmax(X)]
x, y = np.where(X == argmax)
X, list(zip(x,y))

(array([[0.24286839, 0.34311144, 0.50788229, 0.10594458, 0.47030419,
         0.97473467, 0.266392  , 0.03061876, 0.81895081, 0.85746228],
        [0.05151677, 0.68674012, 0.32178307, 0.59076386, 0.00950596,
         0.52696822, 0.75162581, 0.30426881, 0.51621592, 0.87502671],
        [0.83463713, 0.60437179, 0.70341946, 0.06039483, 0.10563672,
         0.73456494, 0.75609519, 0.85567751, 0.01632557, 0.65443262],
        [0.73003603, 0.30285573, 0.14420154, 0.09085481, 0.1663437 ,
         0.76400955, 0.69328487, 0.44666598, 0.84979408, 0.44593994],
        [0.90720589, 0.00585443, 0.1007091 , 0.59978066, 0.78015933,
         0.07539791, 0.75743848, 0.42527272, 0.70483218, 0.98543437],
        [0.14964149, 0.73783353, 0.82428794, 0.45622788, 0.75353683,
         0.35315562, 0.80092862, 0.00313732, 0.23932983, 0.1883522 ],
        [0.78904144, 0.8900362 , 0.19236542, 0.34666755, 0.81202164,
         0.9560341 , 0.33433775, 0.604108  , 0.79312373, 0.66817807],
        [0.15988698, 0.8826

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [7]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
distances = np.sum((X - y) * (X - y), axis=1)

X, \
y, \
X[np.argmin(distances), :]

(array([[0.61701072, 0.87254788],
        [0.16163504, 0.89676422],
        [0.91072591, 0.16375157],
        [0.09231831, 0.35122826],
        [0.35951908, 0.4572776 ],
        [0.73606361, 0.84158167],
        [0.77214151, 0.89830083],
        [0.48176282, 0.05308386],
        [0.97626133, 0.86977363],
        [0.8425673 , 0.0528405 ]]),
 array([[0.81299082, 0.10266731]]),
 array([0.8425673, 0.0528405]))

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [8]:
def f(x):
    if x < 0:
        return x ** 2 + 2 * x + 6
    if 0 <= x <= 2:
        return x + 6
    if x >= 2:
        return x ** 2 + 4 * x - 4

x = np.linspace(-3, 3, 100)

list(map(f, x))

[9.0,
 8.761248852157943,
 8.529843893480258,
 8.305785123966942,
 8.089072543617998,
 7.879706152433425,
 7.677685950413223,
 7.483011937557392,
 7.295684113865932,
 7.115702479338843,
 6.943067033976125,
 6.777777777777777,
 6.619834710743801,
 6.469237832874196,
 6.325987144168962,
 6.190082644628099,
 6.061524334251607,
 5.940312213039485,
 5.8264462809917354,
 5.719926538108356,
 5.620752984389348,
 5.528925619834711,
 5.444444444444445,
 5.367309458218549,
 5.297520661157025,
 5.235078053259871,
 5.179981634527089,
 5.132231404958677,
 5.0918273645546375,
 5.058769513314968,
 5.033057851239669,
 5.014692378328742,
 5.003673094582186,
 5.0,
 5.003673094582186,
 5.014692378328742,
 5.033057851239669,
 5.058769513314968,
 5.0918273645546375,
 5.132231404958678,
 5.179981634527089,
 5.235078053259872,
 5.297520661157025,
 5.367309458218549,
 5.444444444444445,
 5.528925619834711,
 5.620752984389348,
 5.719926538108356,
 5.8264462809917354,
 5.940312213039486,
 6.03030303030303,
 6.09

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [9]:
X = np.random.random((10, 10))

(X.T - X.mean(axis=1)).T, (X.T - X.mean(axis=1)).T.mean(axis=1)

(array([[-0.2693206 , -0.09366581, -0.1624934 ,  0.1266542 ,  0.18215973,
          0.02013824,  0.50911459,  0.04863074, -0.18787703, -0.17334066],
        [ 0.04928751, -0.37745118,  0.3078158 , -0.34806411, -0.36152662,
          0.32656711,  0.28514177, -0.08053233,  0.37747312, -0.17871108],
        [-0.12195415, -0.41345968,  0.01420718,  0.35961875,  0.32268798,
         -0.2988042 , -0.00869445,  0.01380874,  0.30491572, -0.1723259 ],
        [-0.28097842,  0.46096808, -0.40849349, -0.1605039 ,  0.5281454 ,
         -0.36354153, -0.20854655,  0.45336951, -0.18952338,  0.16910426],
        [ 0.19097733,  0.01318347, -0.16254721, -0.21222595, -0.13479823,
         -0.26103177,  0.09225544,  0.56776953, -0.05765715, -0.03592547],
        [-0.0378403 ,  0.2703865 , -0.18839426, -0.3163442 ,  0.11570781,
          0.401852  ,  0.13103723, -0.15593429,  0.19233006, -0.41280054],
        [ 0.34628504,  0.3151602 , -0.29686733,  0.19979627, -0.15724494,
          0.31618805, -0.3576854

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [10]:
X = np.random.normal(loc=5, scale=2., size=1000)
X.mean(), X.var()

(5.062974175552384, 4.102824701156032)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [11]:
x = np.arange(5)
x_transposed = x.reshape(5, 1)
x = x + x_transposed
x = x % 5
x

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [12]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 0, 1, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [13]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    values = s * np.random.random(c)
    res = np.argmin((np.cumsum(x) <= values.reshape(-1, 1)), axis=1)
    return res

            
sample([50, 3, 1, 7, 20], 5)

array([4, 1, 4, 0, 0])